### PR TITLE
Expose some internal code to make this package more usable

### PR DESCRIPTION
**Pull request by EucalyptusLabs**

### CODE REVIEW

**Comment by EucalyptusLabs** [comment]
As, requested, here's the cleaned up PR.

**Comment by tim-eucalyptus** [comment]
Thank you for merging. Would you please create a new release version?

**Comment by tim-eucalyptus** [comment]
when can you create a new release?

**Comment by xclud** [comment]
I have another issue open for the next release.

Meanwhile you can reference the package from git.

```
  dependency_overrides:
    web3dart:
      git:
        url: https://github.com/xclud/web3dart.git
```

**Pull request merged**
